freebsd_instance:
  image_family: freebsd-13-0

test_task:
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  env:
    CIRRUS_WORKING_DIR: /go/src/github.com/$CIRRUS_REPO_FULL_NAME
    CGO_CFLAGS: -I/usr/local/include
    CGO_LDFLAGS: -L/usr/local/lib
  install_script: pkg install -y gpgme git go
  get_script: go get -t -v ./...
  build_script: go build ./...
  test_script: go test -v ./...
