language: go
go:
- "1.12.x"
  arch: amd64
- "1.12.x"
  arch: ppc64le
- master
  arch: amd64
- master
  arch: ppc64le
  
matrix:
  allow_failures:
    - go: master
  
  fast_finish: true
branches:
  only:
  - develop
  - master
env:
  - GO111MODULE=on CGO_CFLAGS=-I/usr/local/include CGO_LDFLAGS=-L/usr/local/lib
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgpgme11 libgpgme11-dev libassuan-dev libassuan0 libgpg-error0 gnupg2
script:
  - make
  - make test
